title: "ACMC2020: Inclusion"
description: The Australasian Computer Music Conference
sitename: ACMC2020
baseurl: ""
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
